### ISSUE TITLE
test_eeglocations fails

### ISSUE THREAD

**Issue by mbillingr** [scot-dev/scot#153]
We got the following failed test on Travis, in an unrelated PR.

We should figure out why this happened, and prevent it from happening again. (Maybe random seed?)

```
======================================================================
FAIL: test_eeglocations (scot.tests.test_eegtopo.test_warp.TestWarpLocations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scot-dev/scot/scot/tests/test_eegtopo/test_warp.py", line 53, in test_eeglocations
    assert_allclose(np.sum(warp**2, axis=1), 1, atol=1e-12)  # all locations on unit shpere
  File "/home/travis/miniconda3/envs/testenv/lib/python3.5/site-packages/numpy/testing/utils.py", line 1359, in assert_allclose
    verbose=verbose, header=header)
  File "/home/travis/miniconda3/envs/testenv/lib/python3.5/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-12
(mismatch 19.736842105263165%)
 x: array([ 1.      ,  1.      ,  1.      ,  1.      ,  1.      ,  1.      ,
        1.      ,  1.      ,  1.      ,  1.      ,  1.      ,  1.      ,
        1.      ,  1.000001,  1.      ,  1.      ,  1.000005,  1.      ,...
 y: array(1)
```

After restarting once, we got `nan`s. Seems suspiciously random to me.

After restarting once again, the test passed.

**Comment by mbillingr** [comment]
I do not know what causes this arbitrary behavior. The test sets a seed before generating random test data.

The function, that I could imagine to cause trouble is `scipy.optimize.minimize()`. Maybe it does not behave consistently? However, I don't think any randomness is involved in the algorithm.

**Comment by cle1109** [comment]
Let's wait and see if this pops up again.

**Comment by mbillingr** [comment]
I hate this :)

**Comment by cbrnr** [comment]
Closing since I didn't see this error in the last PRs.
